TTTS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = '北科老茶後台管理系統'
admin.site.site_title = '北科老茶'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')), 
    path('', include('storeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeApp/urls.py
from django.urls import path

from . import views

app_name = 'storeApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('user_setting/', views.user_setting, name='user_setting'),
    path('user_setting/edit_password/', views.edit_password, name='edit_password'),
    path('search/', views.search, name='search'),
    path('account_panel/', views.account_panel, name='account_panel'),
    path('teas/', views.teas, name='teas'),
    path('teas/<str:fk>/', views.teas_type, name='teas_type'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('regesiter/', views.regesiter, name='regesiter'),
    path('contact/', views.contact, name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_detail/<int:pk>/', views.order_detail, name='order_detail'),
    path('productQuantity/<str:ids>',views.productQuantity,name="productQuantity"),
    path('product_record',views.product_record,name="product_record"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),    
]

base/models.py
from django.db import models

# Create your models here.

storeApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import Http404, JsonResponse
from django.views import generic
from django.http import HttpResponseForbidden
from django.http import HttpResponse
from django.forms.models import modelform_factory
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import auth
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
import json
import math
from pprint import pprint
from .models import *
from .productDiscountItem import ProductDiscountItem, getProductDiscountList

# Create your views here.

teas_pageOne = 1  # first page


def home(request):
    types = TeaType.objects.all()
    newoffers = list(Product.objects.all())
    newoffers.reverse()
    newoffers = newoffers[:4]
    products = getProductDiscountList(newoffers)
    return render(request, 'storeApp/index.html', locals())


def search(request):
    types = TeaType.objects.all()
    if 'page' in request.GET and 'quireText' in request.GET:
        search_text = request.GET['quireText']
        if request.GET['page'] == '':
            page = 1
        else:
            page = int(request.GET['page'])
    elif 'quireText' in request.GET:
        search_text = request.GET['quireText']
        page = 1
    # 取出總頁數
    products = Product.objects.filter(name__contains=search_text)
    total_page = math.ceil(len(products) / 9)
    # 計算上、下頁
    previous_page = page - 1
    next_page = page + 1 if total_page >= page + 1 else 0
    # 變成可迭代物件
    total_page = range(1, total_page+1)
    # 取好 9 個商品
    products = getProductDiscountList(
        list(products)[(page - 1) * 9:page * 9])
    return render(request, 'storeApp/search.html', locals())


def user_panel(request):
    if not request.user.is_authenticated:
        return redirect('storeApp:login')
    if request.user.is_authenticated:
        types = TeaType.objects.all()
        # 取得目前使用者的訂單
        orders = Order.objects.filter(own_user=request.user)
        #
        order_contain_products = OrderContainProduct.objects.all()
        order_list = []
        for order in orders:
            order_list.append(
                {'order_id': order.id, 'items': order_contain_products.filter(order=order)})
        return render(request, 'storeApp/user_panel.html', locals())
    else:
        return redirect('storeApp:login')


def user_setting(request):
    types = TeaType.objects.all()
    if not request.user.is_authenticated:
        return redirect('storeApp:login')
    return render(request, 'storeApp/user_setting.html', locals())


@require_http_methods(["POST"])
def edit_password(request):
    if request.is_ajax():
        username = request.user.username
        old_passwd = request.POST.get('old_passwd', '')
        new_passwd = request.POST.get('new_passwd_again', '')
        data = {}
        data['status'] = db_change_password(username, old_passwd, new_passwd)
        data['url'] = '/login/'
        return HttpResponse(json.dumps(data))


def account_panel(request):
    if not request.user.is_authenticated:
        return redirect('storeApp:login')
    types = TeaType.objects.all()
    return render(request, 'storeApp/account_panel.html', locals())


def productQuantity(request, ids):
    ans = []
    try:
        if ids[0] != "[":
            id = int(ids)
            ans = float(Product.objects.get(pk=id).amount)
        else:
            ids = json.loads(ids)
            ans = [float(x.amount)
                   for x in list(Product.objects.filter(id__in=ids).all())]
        return HttpResponse(json.dumps(ans))
    except:
        return HttpResponse(-1)


def teas(request):
    types = TeaType.objects.all()
    teas = Product.objects.all()
    if 'page' in request.GET:
        if request.GET['page'] == '':
            page = 1
        else:
            page = int(request.GET['page'])
    else:
        page = 1
    # 取出總頁數
    total_page = math.ceil(len(teas) / 9)
    # 計算上、下頁
    previous_page = page - 1
    next_page = page + 1 if total_page >= page + 1 else 0
    # 變成可迭代物件
    total_page = range(1, total_page+1)
    # 取好 9 個商品
    teas = getProductDiscountList(list(teas)[(page - 1) * 9:page * 9])

    return render(request, 'storeApp/teas.html', locals())


def teas_type(request, fk):
    麵包屑 = fk
    types = TeaType.objects.all()
    products = Product.objects.all()
    teas = products.filter(tea_type=types.get(name=fk))
    if 'page' in request.GET:
        if request.GET['page'] == '':
            page = 1
        else:
            page = int(request.GET['page'])
    else:
        page = 1
    # 取出總頁數
    total_page = math.ceil(len(teas) / 9)
    # 計算上、下頁
    previous_page = page - 1
    next_page = page + 1 if total_page >= page + 1 else 0
    # 變成可迭代物件
    total_page = range(1, total_page+1)
    # 取好 9 個商品
    teas = getProductDiscountList(list(teas)[(page - 1) * 9:page * 9])
    return render(request, 'storeApp/teas.html', locals())


ORDER_STATUS = {'1': '已送出', '2': '處理中', '3': '已完成'}


def order_detail(request, pk=None):
    if request.user.is_authenticated:
        types = TeaType.objects.all()
        orders = Order.objects.filter(own_user=request.user)
        order = get_object_or_404(orders, id=pk)
        order.status = ORDER_STATUS[order.status]
        products = OrderContainProduct.objects.filter(order=order)

        return render(request, 'storeApp/order_detail.html', {'order': order, 'products': list(products), 'types': types})
    else:
        return redirect('storeApp:login')


def order_list(request):
    types = TeaType.objects.all()
    orders = Order.objects.filter(own_user=request.user)
    for i in orders:
        i.status = ORDER_STATUS[i.status]
    oneOrder = []
    for i in reversed(orders):
        oneOrder.append(
            {'order': i, 'products': OrderContainProduct.objects.filter(order=i)})
    return render(request, 'storeApp/order_list.html', locals())


@require_http_methods(['POST', 'GET'])
def login(request):
    if request.user.is_authenticated:
        return redirect('storeApp:home')
    if request.method == 'POST':
        name = request.POST['username']  # 取得表單傳送的帳號、密碼
        password = request.POST['password']
        user = auth.authenticate(username=name, password=password)  # 使用者驗證
        if user is not None:  # 若驗證成功，以 auth.login(request,user) 登入
            if user.is_active:
                auth.login(request, user)
                message = '登入成功!'
                # 登入成功產生一個 Session，重導到<index.html>
                return redirect('storeApp:home')
            else:
                message = '帳號尚未啟用!'
        else:
            message = '登入失敗!'
            return render(request, 'storeApp/login.html', locals())
    return render(request, 'storeApp/login.html', locals())


@login_required
def logout(request):
    auth.logout(request)  # 登出成功清除 Session，重導到<index.html>
    return redirect('storeApp:home')


@require_http_methods(['POST', 'GET'])
def regesiter(request):
    types = TeaType.objects.all()
    if request.method == 'POST':
        data = request.POST
        try:
            user = User.objects.get(username=data['username'])
        except:
            user = None  # 若 username 不存在則設定為 None
        if user != None:
            message = user.username + " 帳號已經建立! "
            return render(request, 'storeApp/regesiter.html', locals())
        else:  # 建立 username 帳號
            user = User.objects.create_user(
                username=data['username'], email=data['email'], password=data['password'])
            user.first_name = data['first_name']
            user.last_name = data['last_name']
            user.is_staff = "False"
            user.save()  # 將資料寫入資料庫
            # 若成功建立，重新導向至登入頁面
            return redirect("storeApp:login")
    else:
        return render(request, 'storeApp/regesiter.html', locals())


def contact(request):
    types = TeaType.objects.all()
    return render(request, 'storeApp/contact.html', locals())


def checkout(request):
    # 茶類型
    types = TeaType.objects.all()
    # 運費
    shippingPrice = list(Store.objects.all())[0].freight
    # 運費折扣
    try:
        shippingDiscount = [x for x in list(
            ShippingDiscount.objects.all()) if x.isValidNow()][-1]
    except:
        shippingDiscount = None

    if request.method == 'GET':
        # 事件折扣
        eventDiscounts = [x for x in list(
            SeasoningDiscount.objects.all()) if x.isValidNow()]
        return render(request, 'storeApp/checkout.html', locals())

    elif request.method == 'POST':
        # 登入驗證
        if not request.user.is_authenticated:
            return redirect('storeApp:login')
        # 初始化總價
        total_price = 0
        # 解析收到的資料
        datas = json.loads(request.POST['items'])
        address=request.POST['address']

        # 計算原總價
        for data in datas:
            total_price += Product.objects.get(
                id=data['uid']).get_discount_price()['price'] * data['quantity']
        try:
            # 拿出所選的折扣
            eventDiscount = SeasoningDiscount.objects.get(
                id=json.loads(request.POST.get("eventDiscount", ''))["id"])
        except:
            eventDiscount = None

        if eventDiscount and eventDiscount.isValidNow():
            # 折價券折扣計算後的值
            total_price -= eventDiscount.discountValue(total_price)

        if shippingDiscount and shippingDiscount.isValidNow():
            # 運費折扣後
            total_price = shippingDiscount.calculate_price(
                total_price, shippingPrice)

        order = Order(own_user=request.user, total_price=total_price, address=address)
        order.save()

        for data in datas:
            product = Product.objects.get(id=data['uid'])
            OrderContainProduct.objects.create(
                order=order, product=product, purchase_quantity=data['quantity'])

storeApp/templates/storeApp/accountPanel.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
<li>
  <!-- username -->
  <a href="{% url 'storeApp:userPanel' %}">{{ user.username }}</a>
  <!-- username -->
</li>
<li class="active">
  帳號設定
</li>
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<!-- //插入區 -->
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="bheader mt-3">帳號設定</h2>
      <a class="glyphicon glyphicon-menu-left" href="{% url 'storeApp:userPanel' %}"></a>
      <div class="container my-1">基本資料</div>
      <div class="list-group">
        <a class="list-group-item  list-group-item-action" href="{% url 'storeApp:userSetting' %}">個人檔案設定</a>
      </div>
      <div class="container my-1">其他</div>
      <div class="list-group">
        <a class="list-group-item list-group-item-action">刪除帳號申請</a>
        <a href="{% url 'storeApp:logout' %}" class="list-group-item list-group-item-action text-light bg-secondary">登出帳號</a>
      </div>
    </div>
  </div>
</div>
<!-- //插入區 -->
{% endblock content %}

storeApp/templates/storeApp/account_panel.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
<li>
  <!-- username -->
  <a href="{% url 'storeApp:user_panel' %}">{{ user.username }}</a>
  <!-- username -->
</li>
<li class="active">
  帳號設定
</li>
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<!-- //插入區 -->
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="bheader mt-3">帳號設定</h2>
      <a class="glyphicon glyphicon-menu-left" href="{% url 'storeApp:user_panel' %}"></a>
      <div class="list-group">
        <button type="button" class="list-group-item list-group-item-action" data-toggle="modal" data-target="#exampleModal" style="margin-top: 15px">
          更改密碼
        </button>
        <div>
          {% if message %}
          <a class="h3 text-danger">{{ message }}</a>
          {% endif %}
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header btn-success">
                  <h3 class="modal-title " id="exampleModalLabel">更改密碼</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form id="ajax-contact">
                    <div class="form-group">
                      <label class="mb-2" for="InputOldPassword">請輸入原密碼</label>
                      <input type="password" class="form-control" name="old_passwd" id="InputOldPassword" required=" "
                        placeholder="">
                    </div>
                    <div class="form-group">
                      <label class="mb-2" for="leInputNewPassword">請輸入新密碼</label>
                      <input type="password" class="form-control" name="new_passwd" id="leInputNewPassword" required=" "
                        placeholder="">
                    </div>
                    <div class="form-group">
                      <label class="mb-2" for="InputNewPasswordAgain">請再次輸入新密碼</label>
                      <input type="password" class="form-control" name="new_passwd_again" id="InputNewPasswordAgain"
                        required=" " placeholder="">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-success" data-dismiss="modal">離開</button>
                      <button id="button1" type="button" class="btn btn-success">確認設定</button>
                    </div>
                    {% csrf_token %}
                  </form>
                </div>
            </div>
          </div>
        </div>
        <a href="{% url 'storeApp:logout' %}" class="list-group-item list-group-item-action text-light bg-secondary">登出帳號</a>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'storeApp/js/cheageUaerPassword.js' %}"></script>
<!-- //插入區 -->
{% endblock content %}

storeApp/templates/storeApp/index.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block bc%}
<!-- 首頁沒有麵包屑區塊 -->
{%endblock bc%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<!-- //navigation -->
<!-- main-slider -->
<ul id="demo1">
  <li>
    <img src="{% static 'base/images/navigation.jpg'%}" alt="國韻天香，金枝玉葉" />
    <div class="slide-desc">
      <h3>國韻天香，金枝玉葉</h3>
    </div>
  </li>
  {% for type in types %}
  <li>
    <img src="{{ type.image.url }}" alt="{{ type }}" />
    <div class="slide-desc">
      <h3><a href="{% url 'storeApp:teas_type' type %}" style="color:white">{{ type }}</a></h3>
    </div>
  </li>
  {% endfor %}
</ul>
<!-- //main-slider -->
<!-- //top-header and slider -->
<!-- new -->
{% block new_offers %}
{{ block.super }}
{% endblock new_offers %}
<!-- //new -->
<div class="ban-bottom-w3l">
  <div class="container">
    <div class="col-md-6 ban-bottom3">
      <div class="ban-top" onclick="location.href=`{% url 'storeApp:teas_type' '紅茶' %}`;">
        <img src="{% static 'base/images/紅茶.jpg'%}" class="img-responsive" alt="" />
      </div>
      <div class="ban-img" onclick="location.href=`{% url 'storeApp:teas_type' '綠茶' %}`;">
        <div class=" ban-bottom1">
          <div class="ban-top">
            <img src="{% static 'base/images/烏龍茶.jpg'%}" class="img-responsive" alt="" />
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="col-md-6 ban-bottom" onclick="location.href=`{% url 'storeApp:teas_type' '烏龍茶' %}`;">
      <div class="ban-top">
        <img src="{% static 'base/images/綠茶.jpg'%}" class="img-responsive" alt="" />
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
{% endblock content %}

storeApp/templates/storeApp/order_detail.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
<li><a href="{% url 'storeApp:user_panel' %}">使用者</a></li>
<li><a href="{% url 'storeApp:order_list' %}">訂單管理</a></li>
<li class="active">訂單詳情</li>
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<div class="container checkout">
  <h4 class="productRecord">您的訂單詳情如下 :</h4>
  <!--一筆訂單-->
  {%block order%}
  <div class="item-list">
    <div class="order-item">
      <div class="item-card">
        <!--標頭-->
        <div class="item-header">
          <h4>
            {%block buyer%}
            <h4>訂單日期:{{ order.date }}</h4>
            {%endblock buyer%}
          </h4>
        </div>
        <!--標頭-->
        <br>
        <!--訂單中的商品清單-->
        <div class="item-detail-list">
          <!--訂單中其中一項商品-->
          {%block oneProductOfOrder%}
          {% for i in products %}
          <!--標頭與商品清單分隔線-->
          <div class="border-solid"></div>
          <div class="row d-flex">
            <div class="col-md-9">
              <div class="row">
                <div class=" col-md-3 imgStyle">
                  <!--need to change image-->
                  <img src="{{ i.product.image.url }}" class="item-detail-image" alt="無法顯示">
                </div>
                <div class="item-describe col-md-9 d-flex">
                  {%block orderDescribe%}
                  <pre class="order-describe my-auto">名稱 {{i.product.name}}
數量 {{i.purchase_quantity}}</pre>
                  {%endblock orderDescribe%}
                </div>
              </div>
            </div>
            <div class="col-md-3 price-block my-auto">
              <h4 class="price">
                NT $
                {%block orderPrice%}
                {{i.product.price}}
                {%endblock orderPrice%}
              </h4>
            </div>
          </div>
          {% endfor %}
          {%endblock oneProductOfOrder%}
          <!--訂單中其中一項商品-->
          <!--訂單中的商品清單-->
        </div>
        <!--單筆訂單內與按鈕的分隔線-->
        <div class="border-dash"></div>
        <!--單筆訂單總價與按鈕-->
        <div class="item-button">
            <div class="row buttonContainer">
                <div class="col-md-6">
                  <div class="order-status">
                    <h3 class="form-total">訂單狀態 : {{ order.status }}</h3>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="total-price">
                      <span class="form-total">訂單金額 : </span>
                      <span class="form-price">
                        {%block totalPrice%}
                        {{ order.total_price }}
                        {%endblock totalPrice%}
                      </span>
                    </div>
                </div>
              </div>  
        </div>
        <!--單筆訂單總價與按鈕-->
      </div>
      <!--一筆訂單-->
    </div>
  </div>
  {%endblock order%}
</div>
{% endblock content %}


<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <!-- <th scope="col">品名</th> -->
      <th scope="col">價格</th>
      <th scope="col">數量</th>
    </tr>
  </thead>
  {% for order in order_list %}
  <tbody>
    {% for item in order.items %}
    <tr>
      <th scope="row">{{ order.order_id }}</th>
      <!-- <td>{{ item.product }}</td> -->
      <td>{{ item.product.price }}</td>
      <td>{{ item.purchase_quantity }}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>

storeApp/templates/storeApp/product_record.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
<li><a href="{% url 'storeApp:user_panel' %}">使用者</a></li>
<li class="active">產品購買紀錄</li>
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<div class="container checkout">
  <h4 class="productRecord">產品購買紀錄 :</h4>
  {% if products %}  
  <table class="tableStyle">
      {% for product in products %}  
      <tr class="trStyle">
        <td class="imgStyle"><img src="{{product.image.url}}" class="item-detail-image" alt="{{product.name}}"></td>
        <td><a class="productLink" href="{% url 'storeApp:detail' product.id %}">名稱：{{product.name}}</a></td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <div class="emptyImgDiv">
      <img src="/static/base/images/orderEmpty.png" alt="" class="emptyImg">
      <h4 class="my-2">竟然沒有買過東西</h4>
      <small class="text-muted">快去買個好茶，陶冶一下身心靈吧～</small>
    </div>
    <div class="button-container2">
        <a class=" mybtn" href="/teas/">前往購物</a>
    </div>
    {% endif %}
</div>
{% endblock content %}

storeApp/templates/storeApp/teas.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
{% if 麵包屑 %}
<li class=""><a href="{% url 'storeApp:teas' %}">茶種類</a></li>
<li class="active">{{ 麵包屑 }}</li>
{% else %}
<li class="active">茶種類</a></li>
{% endif %}
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<div class="products">
  <div class="container">
    <div class="col-md-4 products-left">
      {% block categories %}
      <!--- 目錄列表 -->
      <div class="categories">
        <h2>目錄</h2>
        <ul class="cate">
          <li><a href="{% url 'storeApp:teas' %}"><i class="fa fa-arrow-right" aria-hidden="true"></i>所有商品</a></li>
          {% for type in types %}
          <ul>
            <li><a href="{% url 'storeApp:teas_type' type.name %}"><i class="fa fa-arrow-right" aria-hidden="true"></i>
                {{ type.name }}</a></li>
          </ul>
          {% endfor %}
        </ul>
      </div>
      <!--- 目錄列表 -->
      {% endblock categories %}
    </div>
    <div class="col-md-8 products-right">
      <div>
        {% block product %}
        {% for product in teas %}
        <div class="col-md-4 top_brand_left agile_top_brands_grids {%if product.isSoldout %}soldout{%endif%}">
          <div class="hover14 column">
            <div class="agile_top_brand_left_grid">
              <div class="agile_top_brand_left_grid_pos"></div>
              <div class="agile_top_brand_left_grid1">
                <!--- 一筆商品 -->
                <figure>
                  <div class="snipcart-item block">
                    <div class="snipcart-thumb">
                      <!--- 商品照片 -->
                      <a href="{% url 'storeApp:detail' product.id %}"><img title=" " alt=" " src="{{ product.image.url }}"></a>
                      <!--- 商品照片 -->
                      <!--- 商品名稱 -->
                      <p class="productItemTitle">{{ product.name }}</p>
                      <!--- 商品名稱 -->
                      <!--- 商品價錢 -->
                      <div class="high-limit"><h4>NT${{ product.price }} {%if product.isDiscount%}<span>NT${{ product.originPrice }}</span>{%endif%}</h4></div>
                      <!--- 商品價錢 -->
                    </div>
                    <!--加入購物車的小視窗-->
                    <div class="snipcart-details top_brand_home_details">
                      <form action="#" method="post">
                        <fieldset>
                          <input type="hidden" name="cmd" value="_cart">
                          <!--使用者加入的數量-->
                          <input type="hidden" name="add" value="1">
                          <!--使用者加入的數量-->
                          <!--商品名稱-->
                          <input type="hidden" name="item_name" value="{{ product.name }}">
                          <!--商品名稱-->
                          <!-- 產品UID *必填 結帳時回傳給資料庫的資料-->
                          <input type="hidden" name="uid" value="{{ product.id }}">
                          <!-- 產品UID -->
                          <!--商品價格-->
                          <input type="hidden" name="amount" value="{{ product.originPrice }}">
                          <!--商品價格-->
                          {%if product.isDiscount%}
                          <!--折扣價格-->
                          <input type="hidden" name="discount_amount" value="{{ product.discount }}">
                          <!--折扣價格-->
                          {%endif%}
                          <input type="hidden" name="imgSrc" value="{{ product.image.url }}">
                          <input type="submit" name="submit" {%if not product.isSoldout %} value="加入購物車" {%else%} value="已售完" disabled {%endif%} class="button">
                        </fieldset>
                      </form>
                    </div>
                    <!--加入購物車的小視窗-->
                  </div>
                </figure>
                <!--- 一筆商品 -->
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endblock product %}
        <div class="clearfix"> </div>
      </div>
      <!--- 換頁按鈕 -->
      <nav class="numbering">
        <ul class="pagination paging">
          {% if previous_page != 0 %}
          <li>
            <a href="?page={{ previous_page }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}
          {% for i in total_page %}
          {% if i == page%}
          <li class="active"><a href="?page={{ i }}">{{ i }}<span class="sr-only">(current)</span></a></li>
          {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
          {% endfor %}
          {% if next_page != 0 %}
          <li>
            <a href="?page={{ next_page }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--- 換頁按鈕 -->
    </div>
    <div class="clearfix"> </div>
  </div>
</div>
<!--- groceries --->
</div>
</div>
{% endblock content %}

storeApp/templates/storeApp/user_panel.html
{% extends 'storeApp/base.html' %}
{% load static %}
{%block breadcrumb%}
<!--使用者名稱-->
<li class="active">{{ user.username }}</li>
<!--使用者名稱-->
{%endblock breadcrumb%}
<!-- 新增麵包屑 請使用block breadcrumb  %endblock  breadcrumb% 並在上方區塊繼承super-->
{% block content %}
<!-- //插入區 -->
<div class="user_panel-image-container">
    <img src="{% static 'base/images/綠茶.jpg' %}" alt="" class="user_panel-main_image" />
  <!--使用者名稱-->
  <h3>使用者名稱: {{ user.username }}</h3>
  <!--使用者名稱-->
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="tab-content">
        <div id="user" class="tab-pane fade in active">
          <div class="list-group">
            <a class="list-group-item list-group-item-action" href="{% url 'storeApp:account_panel' %}">帳戶設定</a>
            <a class="list-group-item list-group-item-action" href="{% url 'storeApp:order_list' %}">訂單查看</a>
            <a class="list-group-item list-group-item-action" href="{% url 'storeApp:product_record' %}">產品購買紀錄</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- //插入區 -->
{% endblock content %}