TTTS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = '北科老茶後台管理系統'
admin.site.site_title = '北科老茶'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')), 
    path('', include('storeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeApp/urls.py
from django.urls import path

from . import views

app_name = 'storeApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('user_setting/', views.user_setting, name='user_setting'),
    path('user_setting/edit_password/', views.edit_password, name='edit_password'),
    path('search/', views.search, name='search'),
    path('account_panel/', views.account_panel, name='account_panel'),
    path('teas/', views.teas, name='teas'),
    path('teas/<str:fk>/', views.teas_type, name='teas_type'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('regesiter/', views.regesiter, name='regesiter'),
    path('contact/', views.contact, name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_detail/<int:pk>/', views.order_detail, name='order_detail'),
    path('productQuantity/<str:ids>',views.productQuantity,name="productQuantity"),
    path('product_record',views.product_record,name="product_record"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),    
]

base/models.py
from django.db import models

# Create your models here.

base/templates/header-footer.html
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <script>const isLogged='{{ user.is_authenticated }}'==="True";</script>
  <link rel="stylesheet" href="{% static 'base/css/bootstrap4.css' %}">
  <title>{% block headTitle%} TaipeiTech Tea Transaction {% endblock headTitle %}</title>
  <!-- for-mobile-apps -->
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="Super Market Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
		  Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
  <script type="application/x-javascript">
				addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
					function hideURLbar(){ window.scrollTo(0,1); }
			  </script>
  <!-- //for-mobile-apps -->
  <link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
  <link href="{% static 'base/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
  <!-- font-awesome icons -->
  <link href="{% static 'base/css/font-awesome.css' %}" rel="stylesheet" />
  <!-- //font-awesome icons -->
  <!-- js -->
  <script src="{% static 'base/js/jquery-1.11.1.min.js'%}"></script>
  <!-- //js -->
  <!---->
  <!-- start-smoth-scrolling -->
  <script src="{% static 'storeApp/js/cartQuantityCheckHandlers.js'%}" type="module"></script>
  <script type="text/javascript" src="{% static 'base/js/move-top.js'%}"></script>
  <script type="text/javascript" src="{% static 'base/js/easing.js' %}"></script>
  <script type="text/javascript">
    jQuery(document).ready(function ($) {
      $(".scroll").click(function (event) {
        event.preventDefault();
        $("html,body").animate(
          { scrollTop: $(this.hash).offset().top },
          1000
        );
      });
    });
  </script>
  <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
  <!-- start-smoth-scrolling -->
</head>

<body>
  <!-- header -->
  <div class="agileits_header">
    <div class="container">
      <div class="w3l_offers"></div>
      <div class="agile-login">
        <ul>
          <!-- 登入登出區塊 預設為登入註冊 修改if condition 還有寫入使用者名稱-->
          {%if user.is_authenticated %}
          <li><a href="{% url 'storeApp:user_panel' %}">{{ user.username }}</a></li>
          <li><a href="{% url 'storeApp:logout' %}">登出</a></li>
          {% else %}
          <li><a href="{% url 'storeApp:regesiter' %}"> 建立帳戶 </a></li>
          <li><a href="{% url 'storeApp:login' %}">登入</a></li>
          {% endif%}
          <li><a href="{% url 'storeApp:checkout' %}">購物車</a></li>
          <li><a href="{% url 'storeApp:contact' %}">幫助</a></li>
        </ul>
      </div>
      <div class="product_list_header">
        <form action="#" method="post" class="last">
          <input type="hidden" name="cmd" value="_cart" />
          <input type="hidden" name="display" value="1" />
          <button class="w3view-cart" type="submit" name="submit" value="">
            <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
          </button>
        </form>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="logo_products">
    <div class="container">
      <div class="w3ls_logo_products_left1">
        <ul class="phone_email">
          <li>
            <i class="fa fa-phone" aria-hidden="true"></i>線上購買或聯絡我們 :
            02 2771 2171
          </li>
        </ul>
      </div>
      <div class="w3ls_logo_products_left">
        <h1><a href="{% url 'storeApp:home' %}">TaipeiTech Tea</a></h1>
      </div>
      <div class="w3l_search">
        <form action="{% url 'storeApp:search' %}" method="GET">
          <input type="search" name="quireText" placeholder="搜尋商品..." required="" />
          <button type="submit" class="btn btn-default search" aria-label="Left Align">
            <i class="fa fa-search" aria-hidden="true"> </i>
          </button>
          <div class="clearfix"></div>
        </form>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <!-- //header -->
  <!-- navigation -->
  <div class="navigation-agileits">
    <div class="container">
      <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header nav_2">
          <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span> <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'storeApp:home' %}" class="act">首頁</a></li>
            <li><a href="{% url 'storeApp:teas' %}">商品總覽</a></li>
            <!-- Mega Menu -->
            {% for type in types %}
            <li><a href="{% url 'storeApp:teas_type' type.name %}">{{ type.name }}</a></li>
            {% endfor %}
            <li><a href="{% url 'storeApp:contact' %}">聯絡我們</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
  <!-- //navigation -->
  <!-- breadcrumbs -->
  {%block bc%}
  <div class="breadcrumbs">
    <div class="container">
      <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
        <li>
          <a href="{% url 'storeApp:home' %}">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>首頁
          </a>
        </li>
        {%block breadcrumb%}
        {%endblock breadcrumb%}
      </ol>
    </div>
  </div>
  {%endblock bc%}
  <!-- //breadcrumbs -->
  <!-- //插入區-->
  {% block content %}
  {% endblock content %}
  <!-- //插入區-->
  <div class="footer">
    <div class="container">
      <div class="w3_footer_grids">
        <div class="col-md-3 w3_footer_grid">
          <h3>聯絡地址</h3>
          <ul class="address">
            <li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>台北市大安區忠孝東路三段1號</li>
            <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="https://www.ntut.edu.tw">NTUT</a></li>
            <li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>02 2771 2171</li>
          </ul>
        </div>
        <div class="col-md-3 w3_footer_grid">
          <h3>詳細資訊</h3>
          <ul class="info">
            <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="{% url 'storeApp:contact' %}">聯絡我們</a></li>
          </ul>
        </div>
        <div class="col-md-3 w3_footer_grid">
          <h3>商品目錄</h3>
          <ul class="info">
            {% for type in types %}
            <li>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
              <a href="{% url 'storeApp:teas_type' type.name %}">{{ type.name }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="col-md-3 w3_footer_grid">
          <h3>個人資訊</h3>
          <ul class="info">
            <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="{% url 'storeApp:checkout' %}">購物車</a></li>
            {%block accountBar%}
            {%if user.is_authenticated %}
            <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="{% url 'storeApp:logout' %}">登出</a></li>
            {% else %}
            <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="{% url 'storeApp:login' %}">登入</a></li>
            <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="{% url 'storeApp:regesiter' %}">註冊帳號</a></li>
            {% endif %}
            {%endblock accountBar%}
          </ul>
        </div>
        <div class="clearfix"> </div>
      </div>
    </div>
    <div class="footer-copy">
      <div class="container">
        <p>© 2018 Tapei Tech Tea Factory. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
      </div>
    </div>
  </div>
  <div class="footer-botm">
    <div class="container">
      <div class="w3layouts-foot">
        <ul>
          <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
          <li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
          <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
          <li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
        </ul>
      </div>
      <div class="payment-w3ls">
        <img src="{% static 'base/images/card.png'%}" alt=" " class="img-responsive">
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
  <!-- //footer -->
  <!-- Bootstrap Core JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="{%static 'base/js/bootstrap.min.js'%}"></script>
  <!-- top-header and slider -->
  <!-- here stars scrolling icon -->
  <script type="text/javascript">
    $(document).ready(function () {
      $().UItoTop({ easingType: 'easeOutQuart' });
    });
  </script>
  <!-- //here ends scrolling icon -->
  <script src="{%static 'base/js/minicart.min.js'%}"></script>
  <script>
    // Mini Cart
    paypal.minicart.render({
      action: '#'
    });
    if (~window.location.search.indexOf('reset=true')) {
      paypal.minicart.reset();
    }
  </script>
  <!-- main slider-banner -->
  <script src="{%static 'base/js/skdslider.min.js'%}"></script>
  <link href="{%static 'base/css/skdslider.css'%}" rel="stylesheet">
  <script type="text/javascript">
    jQuery(document).ready(function () {
      jQuery('#demo1').skdslider({ 'delay': 5000, 'animationSpeed': 2000, 'showNextPrev': true, 'showPlayButton': true, 'autoSlide': true, 'animationType': 'fading' });
      jQuery('#responsive').change(function () {
        $('#responsive_wrapper').width(jQuery(this).val());
      });
    });
  </script>
  <!-- //main slider-banner -->
  <div class="modal fade" id="exceedStock" tabindex="-1" role="dialog" aria-labelledby="exceedStockLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exceedStockLabel">產品數量已達庫存上限</h5>
        </div>
  <div class="modal-body">
    <p>您設定的產品數量已達庫存上限</p>
    </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">好</button>
  </div>
  </div>
  </div>
  </div>
</body>

</html>